project_id    = "aipartnercatalyst-confluent-01"   
region        = "us-central1"
bucket_name   = "aipartnercatalyst-confluent-bucket"
gar_repo_name = "driftshield-ai-docker"
table_id      = "trip_data_2021"         
