project_id    = "aipartnercatalyst-confluent-01"   
region        = "us-central1"
bucket_name   = "aipartnercatalyst-confluent-bucket"
gar_repo_name = "driftshield-ai-docker"
train_table_id      = "trip_data_2021"   
stream_table_id      = "trip_data_2022"   
dataset_id = "driftshield_ai_dataset"
