project_id    = "aipartnercatalyst-confluent-01"   
region        = "us-central1"
bucket_name   = "aipartnercatalyst-confluent-bucket"
repo_name = "driftshield-ai-docker"
dataset_id = "driftshield_ai_dataset"
training_image_name = "vertexai-custom"
service_account_id = "driftshieldai-sa@aipartnercatalyst-confluent-01.iam.gserviceaccount.com"
